version: '3.1'

services:
  seed:
    image: colinmollenhour/mariadb-galera-swarm
    environment:
      - XTRABACKUP_PASSWORD_FILE=/run/secrets/xtrabackup_password
      - MYSQL_USER=user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - NODE_ADDRESS=^10.0.0.*
    networks:
      - galera_network
    command: seed
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - xtrabackup_password
      - mysql_password
      - mysql_root_password
  node:
    image: colinmollenhour/mariadb-galera-swarm
    environment:
      - XTRABACKUP_PASSWORD_FILE=/run/secrets/xtrabackup_password
      - NODE_ADDRESS=^10.0.0.*
      - HEALTHY_WHILE_BOOTING=1
    networks:
      - galera_network
    command: node galera_seed,galera_node
    deploy:
      replicas: 0
    secrets:
      - xtrabackup_password

volumes:
  mysql-data:
    driver: local

networks:
  galera_network:
    driver: overlay

secrets:
  xtrabackup_password:
    file: .secrets/xtrabackup_password
  mysql_password:
    file: .secrets/mysql_password
  mysql_root_password:
    file: .secrets/mysql_root_password
