version: "3.3"

networks:
  ntw_front:
    external: true

services:

  socat:
    image: devmtl/socatproxy:1.0A
    networks:
      - ntw_front
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.20'
          memory: 16M
        reservations:
          cpus: '0.10'
          memory: 8M
      labels:
        - "traefik.enable=false"

  traefik:
    image: devmtl/traefikfire:1.3.8A
    networks:
      - ntw_front
    ports:
      - mode: ingress
        published: 80
        target: 80
      - mode: host
        published: 8080
        target: 8080
    command: --docker \
      --docker.watch \
      --docker.swarmmode \
      --docker.endpoint=tcp://socat:2375 \
      --docker.domain=traefik \
      --docker.exposedbydefault=true \
      --entryPoints='Name:http' \
      --debug=true \
      --logLevel=WARN \
      --web \
      --web.metrics \
      --web.metrics.prometheus \
      --web.metrics.prometheus.buckets="0.1,0.3,1.2,5.0" \
      --web.address=:8080
    deploy:
      #labels:
      #- "traefik.enable=false"
      mode: replicated
      replicas: 1
      update_config:
        delay: 2s
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
        max_attempts: 5
      resources:
        limits:
          cpus: '0.33'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 64M

#traefik:1.4.0-alpine
#devmtl/traefikfire:1.3.8A
#--docker.endpoint=unix:///var/run/docker.sock \
#--docker.endpoint=tcp://socat:2375 \

#- traefik-pub:/etc/traefik/acme

# no acme
#
# Inspired by https://github.com/containous/traefik/issues/766#issuecomment-335208880
#
# Log options: "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "PANIC"
# https://github.com/containous/traefik/commit/af9b63eaed828f1d548f404fc8b486dd592184e9
#
# by Pascal Andy | # https://twitter.com/askpascalandy
# https://github.com/pascalandy/docker-stack-this
#